#!/usr/bin/env python3
"""
GNS3 Switch Initial Configuration Script
=========================================
Generates and optionally applies the initial Cisco IOS configuration to a
GNS3 virtual switch, including:
- Hostname and management IP
- SSH server setup
- Admin user with privilege 15
- Enable secret

Usage:
    # Generate configuration to stdout
    python scripts/gns3_switch_init.py --generate

    # Generate and save to file
    python scripts/gns3_switch_init.py --generate --output switch_init.cfg

    # Apply configuration via Telnet (for first-time setup before SSH is configured)
    python scripts/gns3_switch_init.py --apply --host 192.168.122.10 --port 5001

    # Apply configuration via SSH (if SSH is already configured)
    python scripts/gns3_switch_init.py --apply --host 192.168.122.10 --ssh
"""

import argparse
import sys
import time

# Configuration parameters (matching the challenge requirements)
SWITCH_HOSTNAME = "SW1"
MANAGEMENT_IP = "192.168.122.10"
MANAGEMENT_PREFIX = "255.255.255.0"
DEFAULT_GATEWAY = "192.168.122.1"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"
ENABLE_SECRET = "admin"
SSH_DOMAIN = "challenge.local"
SSH_KEY_MODULUS = 2048


def generate_config(
    hostname=SWITCH_HOSTNAME,
    mgmt_ip=MANAGEMENT_IP,
    mgmt_mask=MANAGEMENT_PREFIX,
    gateway=DEFAULT_GATEWAY,
    username=ADMIN_USERNAME,
    password=ADMIN_PASSWORD,
    enable_secret=ENABLE_SECRET,
    domain=SSH_DOMAIN,
    rsa_modulus=SSH_KEY_MODULUS,
):
    """
    Generate the Cisco IOS initial configuration as a text string.

    Returns:
        str: Full IOS configuration commands
    """
    config = f"""! ============================================================
! GNS3 Switch Initial Configuration
! Generated by gns3_switch_init.py
! ============================================================

! --- Enter privileged and configuration mode ---
enable
configure terminal

! --- Hostname ---
hostname {hostname}

! --- Disable DNS lookup (prevents console freezes) ---
no ip domain-lookup

! --- Create admin user with privilege 15 ---
username {username} privilege 15 secret {password}

! --- Set enable secret ---
enable secret {enable_secret}

! --- Management interface (VLAN 1) ---
interface Vlan 1
 ip address {mgmt_ip} {mgmt_mask}
 no shutdown
exit

! --- Default gateway ---
ip default-gateway {gateway}

! --- SSH configuration ---
ip domain-name {domain}
crypto key generate rsa modulus {rsa_modulus}
ip ssh version 2
ip ssh time-out 60
ip ssh authentication-retries 3

! --- VTY lines: SSH only ---
line vty 0 4
 transport input ssh
 login local
exit
line vty 5 15
 transport input ssh
 login local
exit

! --- Console configuration ---
line con 0
 logging synchronous
exit

! --- Save configuration ---
end
write memory
"""
    return config


def apply_via_telnet(host, port=5001):
    """
    Apply configuration to a GNS3 switch via Telnet.
    This is used for first-time setup when SSH is not yet configured.
    GNS3 exposes device consoles on Telnet ports starting from 5000.

    Args:
        host: GNS3 server host (usually 127.0.0.1)
        port: Telnet console port (check GNS3 for the assigned port)
    """
    try:
        import telnetlib
    except ImportError:
        print("ERROR: telnetlib is not available (Python 3.13+ removed it).")
        print("Install with: pip install telnetlib3")
        print("Alternatively, use --ssh mode if SSH is already configured.")
        sys.exit(1)

    config = generate_config()
    commands = config.split("\n")

    print(f"Connecting to GNS3 switch console at {host}:{port} via Telnet...")
    print("-" * 60)

    try:
        tn = telnetlib.Telnet(host, port, timeout=10)
    except Exception as e:
        print(f"ERROR: Cannot connect to {host}:{port} - {str(e)}")
        sys.exit(1)

    # Wait for prompt
    time.sleep(2)
    tn.read_very_eager()

    for cmd in commands:
        cmd = cmd.strip()
        if not cmd or cmd.startswith("!"):
            continue
        print(f"  Sending: {cmd}")
        tn.write(cmd.encode("ascii") + b"\n")
        time.sleep(0.5)
        # Read any output
        output = tn.read_very_eager().decode("ascii", errors="ignore")
        if output.strip():
            for line in output.strip().split("\n"):
                print(f"  Switch: {line}")

    # Wait for write memory to complete
    time.sleep(3)
    remaining = tn.read_very_eager().decode("ascii", errors="ignore")
    if remaining.strip():
        print(f"  Switch: {remaining.strip()}")

    tn.close()
    print("-" * 60)
    print("Configuration applied successfully!")
    print(f"SSH should now be available: ssh {ADMIN_USERNAME}@{MANAGEMENT_IP}")


def apply_via_ssh(host, username=ADMIN_USERNAME, password=ADMIN_PASSWORD):
    """
    Apply configuration to a switch via SSH using Netmiko.
    This is used when SSH is already configured but you want to re-apply
    the base configuration.

    Args:
        host: Switch IP address
        username: SSH username
        password: SSH password
    """
    try:
        from netmiko import ConnectHandler
    except ImportError:
        print("ERROR: netmiko is not installed. Run: pip install netmiko")
        sys.exit(1)

    config = generate_config()
    # Filter out non-config commands
    config_commands = [
        line.strip()
        for line in config.split("\n")
        if line.strip() and not line.strip().startswith("!") and line.strip() not in ("enable", "end", "write memory")
    ]

    print(f"Connecting to switch at {host} via SSH...")
    print("-" * 60)

    device = {
        "device_type": "cisco_ios",
        "host": host,
        "username": username,
        "password": password,
        "secret": password,
    }

    try:
        conn = ConnectHandler(**device)
        conn.enable()

        # Re-enter config mode commands
        config_mode_commands = []
        for cmd in config_commands:
            if cmd == "configure terminal":
                continue
            config_mode_commands.append(cmd)

        output = conn.send_config_set(config_mode_commands)
        print(output)

        # Save config
        conn.save_config()
        print("\nConfiguration saved to NVRAM.")

        conn.disconnect()
    except Exception as e:
        print(f"ERROR: {str(e)}")
        sys.exit(1)

    print("-" * 60)
    print("Configuration applied successfully via SSH!")


def main():
    parser = argparse.ArgumentParser(
        description="GNS3 Switch Initial Configuration Script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Print configuration to console
  python scripts/gns3_switch_init.py --generate

  # Save configuration to file
  python scripts/gns3_switch_init.py --generate --output switch_base.cfg

  # Apply via Telnet (GNS3 console port, for first-time setup)
  python scripts/gns3_switch_init.py --apply --host 127.0.0.1 --port 5001

  # Apply via SSH (if SSH already configured)
  python scripts/gns3_switch_init.py --apply --ssh --host 192.168.122.10
        """,
    )

    parser.add_argument("--generate", action="store_true", help="Generate configuration and print to stdout")
    parser.add_argument("--output", type=str, help="Save generated configuration to file")
    parser.add_argument("--apply", action="store_true", help="Apply configuration to the switch")
    parser.add_argument("--ssh", action="store_true", help="Use SSH instead of Telnet for --apply")
    parser.add_argument("--host", type=str, default="127.0.0.1", help="Switch IP or GNS3 server host")
    parser.add_argument("--port", type=int, default=5001, help="Telnet port for GNS3 console (default: 5001)")
    parser.add_argument("--hostname", type=str, default=SWITCH_HOSTNAME, help=f"Switch hostname (default: {SWITCH_HOSTNAME})")
    parser.add_argument("--mgmt-ip", type=str, default=MANAGEMENT_IP, help=f"Management IP (default: {MANAGEMENT_IP})")
    parser.add_argument("--gateway", type=str, default=DEFAULT_GATEWAY, help=f"Default gateway (default: {DEFAULT_GATEWAY})")

    args = parser.parse_args()

    if args.generate or (not args.generate and not args.apply):
        # Default action: generate
        config = generate_config(
            hostname=args.hostname,
            mgmt_ip=args.mgmt_ip,
            gateway=args.gateway,
        )
        if args.output:
            with open(args.output, "w") as f:
                f.write(config)
            print(f"Configuration saved to: {args.output}")
        else:
            print(config)

    if args.apply:
        if args.ssh:
            apply_via_ssh(host=args.host)
        else:
            # For telnet, --host is the GNS3 server (127.0.0.1) and --port is the console port
            apply_via_telnet(host=args.host, port=args.port)


if __name__ == "__main__":
    main()
